#!/usr/bin/env python3
"""Assemble the single-file Union Invitational artifact.

Compresses the hole diagrams to WebP data URIs, flattens the ES modules into
one inline script (no bundler, no network), and writes dist/union-invitational.html.
"""
import base64, io, json, os, re, sys, glob, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src')
DIST = os.path.join(ROOT, 'dist')
WEB = os.path.join(SRC, 'assets', 'web')

MODULE_ORDER = ['data', 'config', 'rules', 'resort', 'weather', 'engine', 'dbsupa', 'store', 'app']

"""Two copies come out of one source. The artifact keeps the platform store it
   already holds a real tournament in; the installable app talks to the book's
   own database. Emitting both every time means neither can be forgotten, and
   the wrong one can never be published by mistake."""
SUPABASE_URL = 'https://zolsghkbgceularukood.supabase.co'
SUPABASE_KEY = 'sb_publishable_g8feql6XYrOP60S6bFNz9A_rTKMPrZw'

EXPORT_RE = re.compile(r'^export\s+(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)', re.M)
IMPORT_RE = re.compile(r"^import\s+(.+?)\s+from\s+'\./(\w+)\.js';\s*$", re.M)


def build_images(force=False):
    """Re-encode the extracted PNGs as WebP and emit the data-URI table."""
    out_js = os.path.join(SRC, 'assets', 'images.js')
    if os.path.exists(out_js) and not force:
        return out_js
    from PIL import Image
    os.makedirs(WEB, exist_ok=True)
    table = {}
    for f in sorted(glob.glob(os.path.join(SRC, 'assets', 'holes', '*.png'))):
        key = os.path.basename(f)[:-4]
        im = Image.open(f).convert('RGBA')
        buf = io.BytesIO(); im.save(buf, 'WEBP', quality=82, method=6)
        d = buf.getvalue()
        open(os.path.join(WEB, key + '.webp'), 'wb').write(d)
        table[key] = 'data:image/webp;base64,' + base64.b64encode(d).decode()
    for key, fn in (('course_aspendos', '1168e907-ae08-408a-9ce8-f178f078bf3f.jpg'),
                    ('course_olympos', '8d395123-ac87-4fb0-86d3-b9434cbdeb2a.jpg')):
        im = Image.open(os.path.join(SRC, 'assets', 'brand', fn)).convert('RGB')
        buf = io.BytesIO(); im.save(buf, 'WEBP', quality=80, method=6)
        d = buf.getvalue()
        open(os.path.join(WEB, key + '.webp'), 'wb').write(d)
        table[key] = 'data:image/webp;base64,' + base64.b64encode(d).decode()
    hero = os.path.join(SRC, 'assets', 'brand', '463041d4-578c-40c2-82ab-413ba30c2b68.jpg')
    im = Image.open(hero).convert('RGB')
    buf = io.BytesIO(); im.save(buf, 'WEBP', quality=80, method=6)
    d = buf.getvalue()
    open(os.path.join(WEB, 'hero.webp'), 'wb').write(d)
    table['hero'] = 'data:image/webp;base64,' + base64.b64encode(d).decode()
    # The resort's own site plan, if we have been given a copy of it. The tab
    # draws its own schematic when we have not, so this is allowed to be absent
    # and the build must not fall over when it is.
    # The site plan is the one picture in the book that gets magnified, so it
    # keeps every pixel it came with. It used to be shrunk to 1800 and then
    # squeezed at quality 82 on top of an already lossy JPEG, and the zoom was
    # magnifying the compression as much as the drawing. The master is the
    # lossless PNG now, kept at its own size, encoded once and gently.
    plan = os.path.join(SRC, 'assets', 'brand', 'resort-map.png')
    if os.path.exists(plan):
        im = Image.open(plan).convert('RGB')
        buf = io.BytesIO(); im.save(buf, 'WEBP', quality=95, method=6)
        d = buf.getvalue()
        open(os.path.join(WEB, 'resortmap.webp'), 'wb').write(d)
        table['resortmap'] = 'data:image/webp;base64,' + base64.b64encode(d).decode()

    # The photograph at the head of The Titanic tab. Optional, like the plan.
    rhero = os.path.join(SRC, 'assets', 'brand', 'resort-hero.jpg')
    if os.path.exists(rhero):
        im = Image.open(rhero).convert('RGB')
        im.thumbnail((1600, 1600), Image.LANCZOS)
        buf = io.BytesIO(); im.save(buf, 'WEBP', quality=80, method=6)
        d = buf.getvalue()
        open(os.path.join(WEB, 'resorthero.webp'), 'wb').write(d)
        table['resorthero'] = 'data:image/webp;base64,' + base64.b64encode(d).decode()

    crest = os.path.join(SRC, 'assets', 'brand', 'efed30fc-173f-48a7-b168-923ebf5d103f.png')
    im = Image.open(crest).convert('RGBA')
    im.thumbnail((620, 620), Image.LANCZOS)
    buf = io.BytesIO(); im.save(buf, 'WEBP', quality=88, method=6)
    d = buf.getvalue()
    open(os.path.join(WEB, 'crest.webp'), 'wb').write(d)
    table['crest'] = 'data:image/webp;base64,' + base64.b64encode(d).decode()
    with open(out_js, 'w') as fh:
        fh.write('// GENERATED by tools/build.py — do not edit by hand.\n')
        fh.write('window.UI_IMAGES = ' + json.dumps(table) + ';\n')
    return out_js


def flatten(name):
    """Turn one ES module into an IIFE that returns its exports."""
    src = open(os.path.join(SRC, name + '.js'), encoding='utf-8').read()
    names = EXPORT_RE.findall(src)
    aliases = []
    for clause, dep in IMPORT_RE.findall(src):
        clause = clause.strip()
        m = re.match(r'^\*\s+as\s+([A-Za-z_$][\w$]*)$', clause)
        aliases.append('const %s = __m_%s;' % (m.group(1), dep) if m
                       else 'const %s = __m_%s;' % (clause, dep))
    body = IMPORT_RE.sub('', src)
    body = re.sub(r'^export\s+', '', body, flags=re.M)
    return ('const __m_%s = (function(){\n%s\n%s\nreturn {%s};\n})();\n'
            % (name, '\n'.join(aliases), body, ', '.join(names)))


def main():
    force = '--images' in sys.argv
    images_js = build_images(force)
    css = open(os.path.join(SRC, 'styles.css'), encoding='utf-8').read()
    shell = open(os.path.join(SRC, 'index.html'), encoding='utf-8').read()
    # The crest is lifted out of the image table and served first, on its
    # own, with the script that puts it on screen. Everything else in that
    # table is a hole diagram nobody sees for another two taps; the crest is
    # the first thing anyone sees, and behind two and a half megabytes of
    # company it was arriving a second late. One copy, moved to the front —
    # the table gets it back by reference a line later in the shell.
    images = open(images_js, encoding='utf-8').read()
    table = json.loads(images[images.index('{'):images.rindex(';')])
    crest_uri = table.pop('crest', '')
    images = ('// GENERATED by tools/build.py — do not edit by hand.\n'
              + 'window.UI_IMAGES = ' + json.dumps(table) + ';\n')
    opening = ('window.UI_CREST = ' + json.dumps(crest_uri) + ';\n'
               + open(os.path.join(SRC, 'opening.js'), encoding='utf-8').read())
    bundle = '\n'.join(flatten(m) for m in MODULE_ORDER) + '\n__m_app.boot();\n'
    # the Supabase client, bundled by tools/vendor.sh, has to have run before
    # the store looks for window.__supabase
    vendor = os.path.join(SRC, 'vendor', 'supabase.min.js')
    vendor_js = open(vendor, encoding='utf-8').read() if os.path.exists(vendor) else ''
    # a stamp the book can show, so a phone holding an old copy gives itself away
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%d-%H%M')
    bundle = bundle.replace('__BUILD__', stamp)
    os.makedirs(DIST, exist_ok=True)
    for name, url, kkey, vend in (
            ('union-invitational.html', '', '', ''),                    # the artifact
            ('union-invitational-app.html', SUPABASE_URL, SUPABASE_KEY, vendor_js)):
        page = (shell
                .replace('/*STYLES*/', css)
                .replace('/*CREST*/', opening)
                .replace('/*IMAGES*/', images)
                .replace('/*VENDOR*/', vend)
                .replace('/*BUNDLE*/', bundle
                         .replace('__SUPABASE_URL__', url)
                         .replace('__SUPABASE_KEY__', kkey)))
        out = os.path.join(DIST, name)
        open(out, 'w', encoding='utf-8').write(page)
        print('%-46s %.2f MB  %s' % (name, os.path.getsize(out) / 1048576,
                                     'supabase' if url else 'artifact store'))


if __name__ == '__main__':
    main()
