#!/usr/bin/env python3
"""Pull Source Serif 4 down so the book carries its own typeface.

On the artifact the fonts came from Google on every cold load. An installed
book is opened on a golf course in Türkiye with no signal and, quite possibly,
an empty browser cache — and a page whose webfont never arrives falls back to
Georgia, which is not the book. So the faces live next to the app, same
origin, cached by the service worker like everything else.

Only latin and latin-ext are kept: the book is in English and the roster has
no cyrillic or greek in it. IBM Plex Mono is not fetched at all — the
stylesheet aliases --mono to --serif, so it was being downloaded and never
drawn with.

Source Serif 4 is under the SIL Open Font License 1.1, which allows this.
Run: python3 tools/fonts.py      (cached; pass --force to re-fetch)
"""
import os, re, sys, hashlib, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src', 'assets', 'fonts')

# a browser UA, or the API serves the older truetype format
UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) '
      'Chrome/120.0.0.0 Safari/537.36')
CSS = ('https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@'
       '0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400&display=swap')
KEEP = ('latin', 'latin-ext')
LICENCE = 'https://raw.githubusercontent.com/adobe-fonts/source-serif/release/LICENSE.md'

BLOCK = re.compile(r'/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{.*?\})', re.S)
FIELD = lambda name, b: (re.search(name + r':\s*([^;]+);', b) or [None, ''])[1].strip()


def get(url, binary=False):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode('utf-8')


def main():
    force = '--force' in sys.argv
    css_out = os.path.join(OUT, 'source-serif.css')
    if os.path.exists(css_out) and not force:
        print('fonts already fetched — pass --force to refresh')
        return
    os.makedirs(OUT, exist_ok=True)

    # Google serves a VARIABLE font, so the file for weight 400 is byte for
    #    byte the file for 600 and 700 — three downloads of one typeface.
    #    Fetch each distinct file once, keyed on its content, and declare the
    #    weight range against it. 746 KB becomes 310 KB.
    for stale in os.listdir(OUT) if os.path.isdir(OUT) else []:
        if stale.endswith('.woff2'):
            os.remove(os.path.join(OUT, stale))

    seen = {}          # content hash -> filename
    faces = []
    for subset, block in BLOCK.findall(get(CSS)):
        if subset not in KEEP:
            continue
        url = re.search(r'url\((https://[^)]+\.woff2)\)', block)
        if not url:
            continue
        style = FIELD('font-style', block) or 'normal'
        weight = FIELD('font-weight', block) or '400'
        blob = get(url.group(1), binary=True)
        key = hashlib.sha256(blob).hexdigest()
        if key not in seen:
            name = 'source-serif-%s-%s.woff2' % (subset, style)
            open(os.path.join(OUT, name), 'wb').write(blob)
            seen[key] = name
        name = seen[key]
        same = next((f for f in faces if f['file'] == name), None)
        if same:
            same['weights'].add(weight)          # one file, several weights
            continue
        faces.append({
            'file': name,
            'style': style,
            'weights': {weight},
            'range': FIELD('unicode-range', block),
            'size': len(blob),
        })

    if not faces:
        sys.exit('nothing came back from Google Fonts — check the network')

    lines = ['/* Source Serif 4, served from the book itself so it renders the',
             '   same with no signal as it does on hotel wifi. SIL Open Font',
             '   License 1.1 — see OFL.txt beside this file.',
             '   GENERATED by tools/fonts.py — do not edit by hand. */']
    for f in faces:
        ws = sorted(int(w) for w in f['weights'])
        weight = str(ws[0]) if len(ws) == 1 else '%d %d' % (ws[0], ws[-1])
        lines += ['@font-face {',
                  "  font-family: 'Source Serif 4';",
                  '  font-style: %s;' % f['style'],
                  '  font-weight: %s;' % weight,
                  '  font-display: swap;',
                  "  src: url('fonts/%s') format('woff2');" % f['file'],
                  '  unicode-range: %s;' % f['range'],
                  '}']
    open(css_out, 'w').write('\n'.join(lines) + '\n')

    try:
        open(os.path.join(OUT, 'OFL.txt'), 'w').write(get(LICENCE))
    except Exception:
        open(os.path.join(OUT, 'OFL.txt'), 'w').write(
            'Source Serif 4 is licensed under the SIL Open Font License 1.1.\n'
            'https://github.com/adobe-fonts/source-serif/blob/release/LICENSE.md\n')

    total = sum(f['size'] for f in faces)
    for f in sorted(faces, key=lambda x: x['file']):
        print('  %-38s %-9s %6.1f KB' % (f['file'],
              ','.join(sorted(f['weights'])), f['size'] / 1024))
    print('\n%d files, %.1f KB in all (a phone fetches only the subsets it draws)'
          % (len(faces), total / 1024))


if __name__ == '__main__':
    main()
