#!/usr/bin/env python3
"""Turn the artifact's tournament into SQL for the book's own database.

The new project seeded itself from the factory book — twenty-three people,
five pairs, nothing played. The tournament that actually exists is the one in
the artifact: a roster that has been pruned, bands set on the practice day,
squads picked, pairings rearranged, tee times, the two course cards as
verified, and a practice round with every card in it.

This reads the documents fetched out of the artifact and writes one SQL file
that puts them in. Every statement is an upsert on the path, so it can be run
twice without making a mess, and the rows the factory seeded that no longer
exist in the real roster are removed rather than left behind as ghosts.

Run: python3 tools/migrate.py <dir-of-fetched-json> [-o docs/migrate.sql]
"""
import json, os, sys, glob, datetime

COLLECTIONS = ('config', 'people', 'pairs', 'scores', 'bbb', 'recaps')


def lit(s):
    """A Postgres string literal, quotes doubled."""
    return "'" + str(s).replace("'", "''") + "'"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('-')]
    src = args[0] if args else None
    out = 'docs/migrate.sql'
    if '-o' in sys.argv:
        out = sys.argv[sys.argv.index('-o') + 1]
    if not src or not os.path.isdir(src):
        sys.exit('usage: python3 tools/migrate.py <dir-of-fetched-json> [-o file.sql]')

    rows = []          # (path, json text)
    keep = {c: set() for c in COLLECTIONS}
    for coll in COLLECTIONS:
        for f in sorted(glob.glob(os.path.join(src, coll, '*.json'))):
            doc_id = os.path.basename(f)[:-5]
            body = json.load(open(f, encoding='utf-8'))
            path = coll + '/' + doc_id
            keep[coll].add(doc_id)
            rows.append((path, json.dumps(body, ensure_ascii=False, separators=(',', ':'))))

    if not rows:
        sys.exit('nothing found under ' + src)

    made = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    L = []
    A = L.append
    A('-- The Union Invitational — the real tournament, moved in')
    A('--')
    A('-- Generated by tools/migrate.py on %s.' % made)
    A('-- Paste into Supabase -> SQL Editor -> New query -> Run.')
    A('-- Safe to run twice: every row is an upsert keyed on its path.')
    A('--')
    A('-- What this carries over, out of the artifact:')
    counts = {c: len(keep[c]) for c in COLLECTIONS if keep[c]}
    for c, n in counts.items():
        A('--   %-8s %d' % (c, n))
    A('--')
    A('-- The roster here is the pruned one. People the factory seeded who are')
    A('-- no longer on the trip are deleted below rather than left as ghosts —')
    A('-- a golfer who was removed once should not come back because the book')
    A('-- changed where it keeps itself.')
    A('')
    A('begin;')
    A('')

    for path, body in rows:
        A('insert into public.docs (path, doc, writer) values')
        A('  (%s, %s::jsonb, %s)' % (lit(path), lit(body), lit('migration')))
        A('  on conflict (path) do update set doc = excluded.doc, writer = excluded.writer;')
    A('')

    A('-- anyone the factory seeded who is not on the real roster')
    for coll in ('people', 'pairs'):
        if not keep[coll]:
            continue
        ids = ', '.join(lit(coll + '/' + i) for i in sorted(keep[coll]))
        A("delete from public.docs where path like %s and path not in (%s);"
          % (lit(coll + '/%'), ids))
    A('')
    A('commit;')
    A('')
    A('-- Did it work?')
    A("select split_part(path, '/', 1) as collection, count(*)")
    A('  from public.docs group by 1 order by 1;')
    A('')
    A('-- Expect:')
    for c, n in counts.items():
        A('--   %-8s %d' % (c, n))

    os.makedirs(os.path.dirname(out) or '.', exist_ok=True)
    open(out, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
    print('%s  %.1f KB' % (out, os.path.getsize(out) / 1024))
    for c, n in counts.items():
        print('  %-8s %d' % (c, n))


if __name__ == '__main__':
    main()
